import os
from crewai import agent, task, crew, process
from langchain.tools import DuckDuckGoSearchRun
from langchain.agents import tool
import gradio as gr

duckduckgo_search = DuckDuckGoSearchRun()

def create_crewai_setup(topic):
 
 researcher = agent(
  role="reasearcher",
  goal=f"""Develop ideas for teaching someone new a subject""",
  backstory=f"""Expert at generating creative and engaging learning topic on different subjects. Skilled in developing topics to reach a wide audience.""",
  verbose=True,
  allow_delegation=True,
  tools=[duckduckgo_search]  
 )


 Writer = agent(
  role="Writer",
  goal="""Write and use the idea that has been developed by the researcher to write a piece of text to explain the topic.""",
  backstory=f"""Expert at generating creative and engaging learning write ups on the topic generated by the researcher. Skilled in writing to teach a wide audience.""",
  verbose=True,
  allow_delegation=True,
 )

 Examiner = agent(
  role="Examiner",
  goal="""Set 3 questions to test the understanding of the created text,along with the correct answers""",
  backstory=f"""Expert in generating test questions based on the topic and write up created to test whether a student fully understood the topic""",
  verbose=True,
  allow_delegation=True,
 )


task1 = Task(
        description=f"""Generate a topic on a subject""",
        agent=researcher,
   )
 
task2 = Task(
        description=f"""create a text based on the topic generated to aid a students understanding""",
        agent=Writer,
  )

task3 = Task(
        description=f"""craft 3 questions along with the correct answers based on the text generated to aid a students understanding""",
        agent=Examiner, 
        ) 
 
product_crew = Crew(
        agents=[researcher, Writer, Examiner],
        tasks=[task1, task2, task3],
        verbose=2,
        process=Process.sequential,
    )
    
crew_result = product_crew.kickoff()
return crew_result

iface = gr.Interface(
    fn=run_crewai_app, 
    inputs="text", 
    outputs="text",
    title="CrewAI Teacher",
    description="Teach."
)

iface.launch()
